### ISSUE TITLE
Integration method deprecated

### ISSUE THREAD

**Issue by asleeis** [upsert/lutron-caseta-pro#26]
I'm not sure when this started, but fairly recently (ish).  Looks like Home Assistant is changing how custom component integrations need to be organized.

```
2019-04-08 13:08:36 ERROR (MainThread) [homeassistant.loader] Error loading 
custom_components.lutron_caseta_pro.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.lutron_caseta_pro.sensor'; 'custom_components.lutron_caseta_pro' is not a package
```

Any chance this could be updated so it won't just stop working?  So far this is the best Caseta integration I've seen and it would be sad to lose it.

**Comment by asleeis** [comment]
Sorry... nevermind.  Looks like I just missed the update.  Thought I had it up-to-date.
