### ISSUE TITLE
Error in casetify.py

### ISSUE THREAD

**Issue by dawiyo** [upsert/lutron-caseta-pro#69]
I'm getting this error on bootup. Any ideas?
***
Logger: homeassistant.setup
Source: custom_components/lutron_caseta_pro/casetify.py:38
First occurred: November 19, 2020, 11:00:44 PM (1 occurrences)
Last logged: November 19, 2020, 11:00:44 PM

Error during setup of component lutron_caseta_pro
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/lutron_caseta_pro/__init__.py", line 161, in async_setup
    await async_setup_bridge(hass, config, fname, bridge)
  File "/config/custom_components/lutron_caseta_pro/__init__.py", line 170, in async_setup_bridge
    devices = await casetify.async_load_integration_report(fname)
  File "/config/custom_components/lutron_caseta_pro/casetify.py", line 38, in async_load_integration_report
    integration_report = json.load(conf_file)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 838 column 1 (char 16111)
```

**Comment by upsert** [comment]
The error indicates an issue with the JSON integration report that would have been pasted into the configurator dialog when the component was setup. Maybe try the setup again?
